# Generated by Django 3.0.7 on 2020-10-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
